appProyectoADB/Web/Controllers/LoginController.cs
using ApplicationCore.Services;
using Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Enum;
using Web.Utils;

namespace Web.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login (LoginUser pLogin)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario oUsuario = null;
            try
            {
                if (ModelState.IsValid)
                {
                    oUsuario = _ServiceUsuario.GetUsuario(pLogin.Identificacion, pLogin.Contrasenia);

                    if (oUsuario != null)
                    {
                        Session["User"] = oUsuario;
                        Log.Info($"Accede {oUsuario.Nombre} {oUsuario.PrimerApellido} {oUsuario.SegundoApellido} con el rol {oUsuario.Rol.IdRol}-{oUsuario.Rol.Descripcion}");
                        TempData["mensaje"] = SweetAlertHelper.Mensaje(string.Format("¡Bienvenido {0} {1}!", oUsuario.Nombre, oUsuario.PrimerApellido), string.Format("Accediendo como: {0}.", oUsuario.Rol.Descripcion), SweetAlertMessageType.success);
                        
                        if (oUsuario.Estado == 0)
                        {
                            ViewBag.NotificationMessage = SweetAlertHelper.Mensaje("¡Inicio fallido!", "Su cuenta está inactiva, consulte al administrador.", SweetAlertMessageType.warning);
                            return View("Index");
                        }

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        Log.Warn($"{pLogin.Identificacion} se intentó conectar  y falló");
                        ViewBag.NotificationMessage = SweetAlertHelper.Mensaje("¡Inicio fallido!", "Usuario o Contraseña incorrectos", SweetAlertMessageType.warning);
                    }
                }
                else {
                    ViewBag.NotificationMessage = SweetAlertHelper.Mensaje("¡Upps!", "Algo salió mal...", SweetAlertMessageType.error);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
         }
        public ActionResult UnAuthorized()
        {
            try
            {
                ViewBag.Message = "No autorizado";

                if (Session["User"] != null)
                {
                    Usuario oUsuario = Session["User"] as Usuario;
                    Log.Warn($"El usuario {oUsuario.Nombre} {oUsuario.PrimerApellido} {oUsuario.SegundoApellido}  con el rol {oUsuario.Rol.IdRol}-{oUsuario.Rol.Descripcion}, intentó acceder una página sin permisos  ");
                }
                else
                {
                    return RedirectToAction("Index", "Login");
                }

                return View();
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData["Redirect"] = "Login";
                TempData["Redirect-Action"] = "Index";
                return RedirectToAction("Default", "Error");
            }
        }
        public ActionResult Logout()
        {
            try
            {
                Log.Info("Usuario desconectado!");
                Session["User"] = null;
                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData["Redirect"] = "Login";
                TempData["Redirect-Action"] = "Index";
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: Usuario/Create
        public ActionResult Signup()
        {
            ViewBag.TipoRoles = listaTipoRol();
            return View();
        }

        private SelectList listaTipoRol(int pIdRol = 0)
        {
            IServiceRol _ServRol = new ServiceRol();
            IEnumerable<Rol> lTipoRoles = _ServRol.GetRol();
            lTipoRoles = lTipoRoles.Where(r => r.IdRol != 1);
            return new SelectList(lTipoRoles, "IdRol", "Descripcion", pIdRol);
        }
    }
}

appProyectoADB/Web/Controllers/ReporteController.cs
using ApplicationCore.Services;
using Infrastructure.Models;
using Infrastructure.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductoCatalogo()
        {
            IEnumerable<Producto> lista = null;
            try
            {

                IServiceProducto _ServiceProducto = new ServiceProducto();
                lista = _ServiceProducto.GetProducto();
                return View(lista);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        public ActionResult graficoBarraSalidasProducto()
        {
            return View();
        }
    }
}

appProyectoADB/Web/Views/Shared/_Footer.cshtml
<hr class="border-secondary mx-5"/>
<div class="container">
    <p>&copy; @DateTime.Now.Year - Almacen del Barrio - Proyecto ISW-711</p>
</div>

appProyectoADB/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap_almacen.min.css")
    @RenderSection("scripts", required: false)
</body>
</html>

appProyectoADB/Web/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE html>

<html lang="es" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")

    <style>

        body {
            background-color: #DDD8EC;
        }

        .marco {
            background-color: #DDD8EC;
            padding: 15px;
        }

        .general {
            background-color: #ffffff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
            border-radius: 12px;
            padding: 20px;
        }
    </style>

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

</head>
<body class="bg-primary">
    <nav class="navbar shadow-sm navbar-expand-lg navbar-dark bg-primary bg-gradient p-0">
        <div class="container-fluid">
            <a class="navbar-brand" href='@Url.Action("Index", "Home")'><img src="~/img/tiendaBG.png" class="mx-auto d-block" /><span>Almac&eacute;n Del Barrio</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    @*<li class="nav-item">
            <img src="~/img/casa.png" class="mx-auto d-block" />
            @Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link" })
        </li>*@
                    <li class="nav-item">
                        <img src="~/img/bolsa.png" class="mx-auto d-block" />
                        @Html.ActionLink("Productos", "Index", "Producto", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <img src="~/img/edificio.png" class="mx-auto d-block" />
                        @Html.ActionLink("Proveedores", "Index", "Proveedor", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <img src="~/img/dinero.png" class="mx-auto d-block" />
                        @Html.ActionLink("Movimientos", "Index", "Registro", null, new { @class = "nav-link" })
                    </li>
                    @*
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reportes</a>
            <div class="dropdown-menu">
                @*
                @Html.ActionLink("Informe Entradas", "LibroCatalogo", "Reporte", null, new { @class = "dropdown-item" })
                @Html.ActionLink("Informe Salidas", "graficoProducto", "Producto", null, new { @class = "dropdown-item" })

                    @Html.ActionLink("Informe Productos", "graficoProducto", "Producto", null, new { @class = "dropdown-item" })
                    </div>
            </li>
                    *@
                    <li class="nav-item dropdown">
                        <img src="~/img/rep.png" class="mx-auto d-block" />
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reportes</a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("Informe Entradas", "reporteEntradasProducto", "Inventario", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Informe Salidas", "reporteSalidasProducto", "Inventario", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Informe Productos", "graficoProducto", "Producto", null, new { @class = "dropdown-item" })
                        </div>
                    </li>

                    <li class="nav-item">
                        <img src="~/img/usuarios.png" class="mx-auto d-block" />
                        @Html.ActionLink("Usuarios", "Index", "Usuario", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <img src="~/img/info.png" class="mx-auto d-block" />
                        @Html.ActionLink("Acerca de", "About", "Home", null, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
            <img src="~/img/lock.png" class="mx-auto d-block" />
            @Html.ActionLink("Cerrar sesión", "Logout", "Login", null, new { @class = "nav-link" })
        </li>*@
                </ul>

                @{
                    string nomUser = "Nombre Usuario";
                    string dcsRol = "Perfil Usuario";
                    Infrastructure.Models.Usuario oUsuario;
                    //Validar si existe en la sesión
                    if (Session["User"] != null)
                    {
                        oUsuario = (Infrastructure.Models.Usuario)Session["User"];
                        if (oUsuario != null)
                        {
                            nomUser = string.Format("{0} {1} {2}.", oUsuario.Nombre, oUsuario.PrimerApellido, oUsuario.SegundoApellido.Substring(0, 1));
                            dcsRol = oUsuario.Rol.Descripcion;
                        }
                    }
                }

                <div class="profile w-auto bg-secondary p-1 rounded-1 shadow-lg">
                    <div class="profile-details d-flex align-items-center">
                        <div class="text-white px-2 fs-1">
                            <i class='bx bxs-user-circle'></i>
                        </div>
                        <div class="text-sm-center text-white px-2 m-1">
                            @if (Session["User"] != null)
                            {
                                <div class="name">@nomUser</div>
                                <hr class="m-0" />
                                <div class="rol">@dcsRol</div>
                            }
                        </div>
                        @if (Session["User"] == null)
                        {
                            <a class="btn btn-outline-primary p-2 mx-2 rounded" href='@Url.Action("Index", "Login")' data-bs-toggle="tooltip" data-bs-placement="left" title="Entrar..."><i class='bx bx-log-in'></i></a>
                        }
                        else
                        {
                            <a class="btn btn-outline-primary p-2 mx-2 rounded" href='@Url.Action("Logout", "Login")' data-bs-toggle="tooltip" data-bs-placement="left" title="Salir..."><i class='bx bx-log-out'></i></a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main>
        <div class="marco">
            <div class="general container-fluid">
                @RenderBody()
            </div>
        </div>
    </main>
    <footer class="page-footer shadow bg-primary bg-gradient text-white text-center mt-auto py-1">
        @Html.Partial("_Footer")
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @*Scripts.Render("~/bundles/popper")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sweetalert")
    @RenderSection("scripts", required: false)

    @if (ViewBag.NotificationMessage != null)
    {
        <script>
            @Html.Raw(@ViewBag.NotificationMessage);
        </script>
    }
</body>
</html>

appProyectoADB/Web/Views/Shared/_Login.cshtml
<!DOCTYPE html>

<html lang="es" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Almacen Del Barrio</title>

    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)

    <style>

        body {
            background-color: #DDD8EC;
        }

        .marco {
            background-color: #DDD8EC;
            padding: 15px;
        }

        .general {
            background-color: #ffffff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
            border-radius: 12px;
            padding: 20px;
        }
    </style>

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-gradient">
        <a class="navbar-brand" href='@Url.Action("Index", "Login")'><img src="~/img/tiendaBG.png" class="mx-auto" /><span class="align-middle mx-1">Almacen Del Barrio</span></a>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item align-baseline text-light fs-3">
                    |
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Login", "Index", "Login", null, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>
    <main>
        <div class="marco">
            <div class="general container-fluid">
                @RenderBody()
            </div>
        </div>
    </main>
    <footer class="page-footer shadow bg-primary text-white text-center mt-auto py-1">
        @Html.Partial("_Footer")
    </footer>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/popper")

    @Scripts.Render("~/bundles/jqueryui")

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sweetalert")

    @RenderSection("scripts", required: false)
    @if (ViewBag.NotificationMessage != null)
    {
        <script>
            @Html.Raw(@ViewBag.NotificationMessage);
        </script>
    }
</body>
</html>

appProyectoADB/Web/Views/Shared/_LoginUser.cshtml
<!DOCTYPE html>

<html lang="es" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Almac&eacute;n Del Barrio</title>

    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)

    <style>

        body {
            background-color: #DDD8EC;
        }

        .marco {
            background-color: #DDD8EC;
            padding: 15px;
        }

        .general {
            background-color: #ffffff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
            border-radius: 12px;
            padding: 20px;
        }
    </style>

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

</head>
<body class="bg-primary">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-gradient">
        <a class="navbar-brand" href='@Url.Action("Index", "Login")'><img src="~/img/tiendaBG.png" class="mx-auto" /><span class="align-middle mx-1">Almac&eacute;n Del Barrio</span></a>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item align-baseline text-light fs-3">
                    |
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Acceso al sistema", "Index", "Login", null, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>
    <main>
        <div class="marco">
            <div class="general container-fluid">
                @RenderBody()
            </div>
        </div>
    </main>
    <footer class="page-footer shadow bg-primary bg-gradient text-white text-center mt-auto py-1">
        @Html.Partial("_Footer")
    </footer>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/popper")

    @Scripts.Render("~/bundles/jqueryui")

    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/sweetalert")

    @RenderSection("scripts", required: false)
    @if (ViewBag.NotificationMessage != null)
    {
        <script>
            @Html.Raw(@ViewBag.NotificationMessage);
        </script>
    }
</body>
</html>

appProyectoADB/Web/Views/Shared/_OrdenCantidad.cshtml
@{ int cantidadProductos = Web.ViewModel.Movimiento.Instancia.GetCountItems();}

<a href="@Url.Action("Create", "Registro")" class="nav-link">
    Orden <span class="badge badge-light">   @cantidadProductos</span>
</a>

@if (@ViewBag.NotiCarrito != null)
{
    <script>
            @Html.Raw(@ViewBag.NotiCarrito);
    </script>
}

appProyectoADB/Web/Views/Shared/_ProductosPorAgotar.cshtml
@model IEnumerable<Infrastructure.Models.Producto>

<div class="card p-1" style="border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
    <div class="card-header mb-1 bg-primary bg-gradient text-white">
        Productos pendientes de reponer.
    </div>
    <div class="card-body bg-light">
        <div class="table-responsive">
            <table class="table table-light table-hover table-striped">
                <tr class="table-primary">
                    <th>
                        @Html.DisplayNameFor(model => model.IdProducto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre_Producto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Descripcion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Precio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CantidadDisponible)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CantidadStockMin)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CantidadStockMax)
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr class="align-middle">
                        <td>
                            @Html.DisplayFor(modelItem => item.IdProducto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre_Producto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Precio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CantidadDisponible)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CantidadStockMin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CantidadStockMax)
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

appProyectoADB/Web/Views/Shared/_TotalEntradas.cshtml
@using Infrastructure.Models
@model IEnumerable<Infrastructure.Models.GestionInventario>

<div class="card text-dark mb-3 p-1" style="border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
    <div class="card-header text-white bg-primary bg-gradient">Entradas registradas para hoy.</div>
    <div class="card-body bg-light">
        <h5 class="card-title">
            Total: @{
                Html.RenderAction("_TotalEntradas", "Inventario");
            } entradas.
        </h5>
    </div>
</div>

appProyectoADB/Web/Views/Shared/_TotalProductos.cshtml
@using Infrastructure.Models
@model IEnumerable<Infrastructure.Models.Producto>

<div class="card text-dark mb-3 p-1" style="border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
    <div class="card-header text-white bg-primary bg-gradient">Total de productos registrados.</div>
    <div class="card-body bg-light">
        <h5 class="card-title">
            Total: @{
                Html.RenderAction("_TotalProductos", "Producto");
            } productos.
        </h5>
    </div>
</div>

appProyectoADB/Web/Views/Shared/_TotalSalidas.cshtml
@using Infrastructure.Models
@model IEnumerable<Infrastructure.Models.GestionInventario>

<div class="card text-dark mb-3 p-1" style="border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
    <div class="card-header text-white bg-primary bg-gradient">Salidas registradas para hoy.</div>
    <div class="card-body bg-light">
        <h5 class="card-title">
            Total: @{
                Html.RenderAction("_TotalSalidas", "Inventario");
            } Salidas.
        </h5>
    </div>
</div>